version: '2'

services:
  registry:
    image: registry:latest
    ports:
      - ${REGISTRY_PORT}:5000
    volumes: 
      - ./certs:/certs  
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:${REGISTRY_PORT}
      REGISTRY_HTTP_TLS_CERTIFICATE: ./certs/dko.crt
      REGISTRY_HTTP_TLS_CERTIFICATE: ./certs/dko.crt
      REGISTRY_HTTP_TLS_KEY: ./certs/dko.key
